### ISSUE TITLE
Gnuradio 3.7 compatibility

### ISSUE THREAD

**Issue by cucim** [jboone/gr-tpms#2]
Hi,
I am getting some errors wih gnu radio 3.7:
Traceback (most recent call last):
  File "/usr/local/bin/tpms_rx", line 30, in <module>
    from gnuradio import analog
  File "/usr/local/lib/python2.7/dist-packages/gnuradio/analog/__init__.py", line 35, in <module>
    from am_demod import *
  File "/usr/local/lib/python2.7/dist-packages/gnuradio/analog/am_demod.py", line 24, in <module>
    from gnuradio import filter
  File "/usr/local/lib/python2.7/dist-packages/gnuradio/filter/__init__.py", line 32, in <module>
    from filter_swig import *
  File "/usr/local/lib/python2.7/dist-packages/gnuradio/filter/filter_swig.py", line 28, in <module>
    _filter_swig = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/gnuradio/filter/filter_swig.py", line 24, in swig_import_helper
    _mod = imp.load_module('_filter_swig', fp, pathname, description)
ImportError: /usr/local/lib/libgnuradio-filter-3.7.4.so.0.0.0: undefined symbol: volk_malloc

**Comment by jboone** [comment]
This project is being used by several people against the newest (3.7.6) release of GNU Radio 3.7, on Linux and Mac OS X. Hopefully, you are able to run against a newer GNU Radio now.
