### ISSUE TITLE
python-3.9 parsing error during make

### ISSUE THREAD

**Issue by rodan** [jboone/gr-tpms#21]
python-2.7 does not complain during compilation of this package, however python3-9 returns this:

[..]
[ 60%] Generating __init__.pyo, ask.pyo, bit_coding.pyo, decode.pyo, fsk.pyo, packet_check.pyo, source.pyo
make[2]: Leaving directory '/dev/shm/portage/net-wireless/gr-tpms-9999/work/gr-tpms-9999_build'
cd /dev/shm/portage/net-wireless/gr-tpms-9999/work/gr-tpms-9999_build/python && /usr/bin/python -O /dev/shm/portage/net-wireless/gr-tpms-9999/work/gr-tpms-9999_build/python_compile_helper.py /dev/shm/portage/net-wireless/gr-tpms-9999/work/gr-tpms-9999/python/__init__.py /dev/shm/portage/net-wireless/gr-tpms-9999/work/gr-tpms-9999/python/ask.py /dev/shm/portage/net-wireless/gr-tpms-9999/work/gr-tpms-9999/python/bit_coding.py /dev/shm/portage/net-wireless/gr-tpms-9999/work/gr-tpms-9999/python/decode.py /dev/shm/portage/net-wireless/gr-tpms-9999/work/gr-tpms-9999/python/fsk.py /dev/shm/portage/net-wireless/gr-tpms-9999/work/gr-tpms-9999/python/packet_check.py /dev/shm/portage/net-wireless/gr-tpms-9999/work/gr-tpms-9999/python/source.py /dev/shm/portage/net-wireless/gr-tpms-9999/work/gr-tpms-9999_build/python/__init__.pyo /dev/shm/portage/net-wireless/gr-tpms-9999/work/gr-tpms-9999_build/python/ask.pyo /dev/shm/portage/net-wireless/gr-tpms-9999/work/gr-tpms-9999_build/python/bit_coding.pyo /dev/shm/portage/net-wireless/gr-tpms-9999/work/gr-tpms-9999_build/python/decode.pyo /dev/shm/portage/net-wireless/gr-tpms-9999/work/gr-tpms-9999_build/python/fsk.pyo /dev/shm/portage/net-wireless/gr-tpms-9999/work/gr-tpms-9999_build/python/packet_check.pyo /dev/shm/portage/net-wireless/gr-tpms-9999/work/gr-tpms-9999_build/python/source.pyo
[ 60%] Built target pygen_apps_364c4
Traceback (most recent call last):
  File "/usr/lib/python3.9/py_compile.py", line 144, in compile
    code = loader.source_to_code(source_bytes, dfile or file,
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/dev/shm/portage/net-wireless/gr-tpms-9999/work/gr-tpms-9999/python/__init__.py", line 33
    from DLFCN import RTLD_GLOBAL as _RTLD_GLOBAL
TabError: inconsistent use of tabs and spaces in indentation

**Comment by rodan** [comment]
how do I attach a file to this stupid tracker?

anyhow, these tabs need to be replaced with 8 spaces and then the package compiles successfully:

diff --git a/python/__init__.py b/python/__init__.py
index 46e0e31..3fead6b 100644
--- a/python/__init__.py
+++ b/python/__init__.py
@@ -30,9 +30,9 @@ try:
     from dl import RTLD_GLOBAL as _RTLD_GLOBAL
 except ImportError:
     try:
-	from DLFCN import RTLD_GLOBAL as _RTLD_GLOBAL
+        from DLFCN import RTLD_GLOBAL as _RTLD_GLOBAL
     except ImportError:
-	pass
+        pass
 
 if _RTLD_GLOBAL != 0:
     _dlopenflags = sys.getdlopenflags()

**Comment by developerfromjokela** [comment]
`autopep8 -i <filename>`
